# Copyright 2019 RStudio, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

language: python
services:
  - docker
python:
  - 3.6
script:
  # --no-binary buildbot is required because buildbot doesn't bundle its tests
  # to binary wheels, but ursabot's test suite depends on buildbot's so install
  # it from source
  - pip install --no-binary buildbot "pytest>=3.9" mock flake8 -e .

  # run linter
  - flake8 ursabot

  # run the worker tests (docker utilities for now)
  - pytest -v ursabot

  # check the buildbot configuration
  - buildbot checkconfig
