# Copyright 2019 RStudio, Inc.
# All rights reserved.
#
# Use of this source code is governed by a BSD 2-Clause
# license that can be found in the LICENSE_BSD file.

language: python
services:
  - docker
python:
  - 3.6
script:
  # --no-binary buildbot is required because buildbot doesn't bundle its tests
  # to binary wheels, but ursabot's test suite depends on buildbot's so install
  # it from source
  - pip install --no-binary buildbot "pytest>=3.9" mock flake8 -e .

  # run linter
  - flake8 ursabot

  # run the worker tests (docker utilities for now)
  - pytest -v ursabot

  # run the arrow project tests
  - pytest -sv projects/arrow

  # check the ursabot buildbot configurations
  - pushd projects/ursabot
  - ursabot -v checkconfig
  - popd

  # check the arrow buildbot configurations
  - pushd projects/arrow
  - ursabot -v checkconfig
  - popd

  # check the top level "ubrella" config, this is the production config, so it
  # requires both ~/.uralabs-pass to be present and pass to be installed
  - sudo apt-get install pass
  - mkdir ~/.ursalabs-pass
  - ursabot -v checkconfig

  # run one of the arrow builders locally
  - pushd projects/arrow
  - ursabot project build 'AMD64 Ubuntu 18.04 C++'
  - popd
