title = 'Ursabot Docker Compose'
url = 'http://localhost:8100/'
webui_port = 8100
database_url = 'postgresql://ursabot:topsecret@db:5432/ursabot'

[github]
token = "invalid_token"

[projects]

  [projects.ursabot]
  enabled = true
  reporters = []

  [projects.arrow]
  enabled = true
  reporters = []

[[workers]]
# docker-on-mac is able to containers for multiple architectures
name = 'local1'
arch = 'amd64'
docker.host = 'tcp://worker1:2375'
docker.hostconfig = { network_mode = 'host' }

[[workers]]
name = 'local2'
arch = 'amd64'
docker.host = 'tcp://worker1:2375'
docker.hostconfig = { network_mode = 'host' }
