# Copyright 2019 RStudio, Inc.
# All rights reserved.
#
# Use of this source code is governed by a BSD 2-Clause
# license that can be found in the LICENSE_BSD file.

###################### Buildmaster specific configurations ####################

# The 'title' string will appear at the top of this buildbot installation's
# home pages (linked to the 'titleURL').
title: 'Ursa-Labs Buildbot'

# The 'buildbotURL' string should point to the location where the buildbot's
# internal web server is visible. This typically uses the port number set in
# the 'webui_port' entry below, but with an externally-visible host name which
# the buildbot cannot figure out without some help.
url:

# Protocols contains information about protocols which master will use for
# communicating with workers. You must define at least 'port' option that
# workers could connect to your master with this protocol.
# 'port' must match the value configured into the workers (with their
# --master option)
worker_port: 9989
webui_port: 4100
database_url: 'sqlite:///ursabot.sqlite'

secrets:
  # setup secret providers, currently on SecretInPass supported
  enabled: true
  # optional, prefer gpg-agent instead
  passphrase:
  directory:

auth:
  # enable authentication, only github oauth is supported
  enabled: false
  roles:
    admin:
      # github organizations whos members are admins
      orgs: []
      # additional user whom admin access should be granted
      users: []
  github:
    client_id: '%(secret:ursabot/github_client_id)s'
    client_secret: '%(secret:ursabot/github_client_secret)s'

hooks:
  github:
    enabled: false
    debug: true
    # secret must be provided during the hook definition on github
    secret: '%(secret:ursabot/github_hook_secret)s'
    # github token used for issuing additional API calls
    tokens:
      - '%(secret:ursabot/github_token)s'

projects:
  ursabot:
    enabled: true
    config: 'projects/ursabot/master.cfg'
    variable: ursabot
  arrow:
    enabled: true
    config: 'projects/arrow/master.cfg'
    variable: arrow
