# The 'title' string will appear at the top of this buildbot installation's
# home pages (linked to the 'titleURL').
title = 'Ursa-Labs Buildbot'

# The 'buildbotURL' string should point to the location where the buildbot's
# internal web server is visible. This typically uses the port number set in
# the 'webui_port' entry below, but with an externally-visible host name which
# the buildbot cannot figure out without some help.
# url =

# Protocols contains information about protocols which master will use for
# communicating with workers. You must define at least 'port' option that
# workers could connect to your master with this protocol.
# 'port' must match the value configured into the workers (with their
# --master option)
worker_port = 9989
webui_port = 4100
database_url = 'sqlite:///ursabot.sqlite'

[secrets]
# setup secret providers, currently on SecretInPass supported
enabled = false
directory = '~/.ursalabs-pass'
# passphrase = optional, prefer gpg-agent instead

[github]
# have to provide repo:status scope for the token and write access to the
# for the repositories in order to support github status_push below
token = '%(secret:ursabot/github_token)s'

  [github.auth]
  # github organizations whos members are admins
  # additional user whom admin access should be granted
  enabled = false
  client_id = '%(secret:ursabot/github_client_id)s'
  client_secret = '%(secret:ursabot/github_client_secret)s'
  # admin = {
  #   orgs = [...]
  #   users = [...]
  # }

  [github.event_hook]
  # Secret must be provided during the hook definition on github.
  debug = true
  enabled = false
  secret = '%(secret:ursabot/github_hook_secret)s'

[schedulers]

  [schedulers.try]
  enabled = false
  port = 4010
  userpass = {}

[projects]

  [projects.arrow]
  enabled = true
  # must be in `owner/repo` format
  name = 'apache/arrow'
  repository = 'https://github.com/apache/arrow'
  reporters = []
  change_sources = []

  [projects.ursabot]
  enabled = true
  # must be in `owner/repo` format
  name = 'ursa-labs/ursabot'
  repository = 'https://github.com/ursa-labs/ursabot'
  reporters = []
  change_sources = []

[reporters]
# global flags for reporters, to enable/disable per project add/remove to/from
# the projects' reporters list

  [reporters.github_status]
  debug = true

  [reporters.github_review]
  debug = true

  [reporters.zulip_status]
  organization = 'ursalabs'
  bot = 'ursabot-bot@ursalabs.zulipchat.com'
  stream = 'ursabot'
  apikey = '%(secret:ursabot/zulip_api_key)s'

[changes]

  [changes.pb]
  enabled = false
  # port = 9041
  # user = ...
  # password = ...

# [[workers]]
# name = 'local'
# arch = 'arm64v8' or 'amd64'
# docker.host = 'tcp://host:port' or 'unix://var/run/docker.sock'
# docker.masterFQDN = '...'
# docker.autopull = true
# docker.alwayspull = true
# # for testing on docker on mac explicitly defined the following reserved host
# docker.masterFQDN = 'host.docker.internal'
# docker.hostconfig.network_mode = 'host'
# docker.hostconfig.cpuset_cpus = '2,3'
