# Copyright 2019 RStudio, Inc.
# All rights reserved.
#
# Use of this source code is governed by a BSD 2-Clause
# license that can be found in the LICENSE_BSD file.

version: '3.5'

services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: topsecret
      POSTGRES_USER: ursabot
      POSTGRES_DB: ursabot
    expose:
      - 5432

  master:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - db:db
      - worker1:worker1
      - worker2:worker2
    volumes:
      - .:/ursabot:delegated
    command: buildbot checkconfig

  worker1:
    image: docker:dind
    privileged: true
    ports:
      - 2375

  worker2:
    image: docker:dind
    privileged: true
    ports:
      - 2375
