version: '3'

volumes:
  data:
    driver: local

services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: topsecret
      POSTGRES_USER: ursabot
      POSTGRES_DB: ursabot
    expose:
      - 5432
    volumes:
      - data:/var/lib/postgresql/data

  master:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - db:db
      - worker1:worker1
      - worker2:worker2
    ports:
      - 8100:8100
    environment:
      URSABOT_ENV: compose
    volumes:
      - .:/ursabot:delegated
    command: /bin/sh -c "buildbot upgrade-master . && buildbot start . && tail -f twistd.log"

  worker1:
    image: docker:dind
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - 2375

  worker2:
    image: docker:dind
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - 2375
