url = 'https://ci.ursalabs.org/'
webui_port = 8010

[projects]

  [projects.ursabot]
  reporters = ['github_status']
  # github hook is enabled so no additional change source is required
  change_sources = []

  [projects.arrow]
  reporters = ['github_comment', 'zulip_status']
  # github hook is enabled so no additional change source is required
  change_sources = []

[github]

  [github.event_hook]
  # disable poller change sources for projects with event_hook set up
  enabled = true
  debug = true

  [github.auth]
  enabled = true

  [github.auth.admin]
  orgs = ['ursa-labs']
  users = ['xhochy', 'kou']

[changes]

  [changes.pb]
  enabled = true
  port = 9041

[schedulers]

  [schedulers.try]
  enabled = true

[[workers]]
name = 'dgx1-1'
arch = 'amd64'
docker.host = 'tcp://ursa-dgx1:2375'
docker.hostconfig = { network_mode = 'host', cpuset_cpus = '0-3,20-23' }

[[workers]]
name = 'dgx1-2'
arch = 'amd64'
docker.host = 'tcp://ursa-dgx1:2375'
docker.hostconfig = { network_mode = 'host', cpuset_cpus = '4-7,24-27' }

[[workers]]
name = 'dgx1-3'
arch = 'amd64'
docker.host = 'tcp://ursa-dgx1:2375'
docker.hostconfig = { network_mode = 'host', cpuset_cpus = '8-11,28-31' }

[[workers]]
name = 'dgx1-4'
arch = 'amd64'
docker.host = 'tcp://ursa-dgx1:2375'
docker.hostconfig = { network_mode = 'host', cpuset_cpus = '12-15,32-35' }

[[workers]]
name = 'dgx1-5'
arch = 'amd64'
docker.host = 'tcp://ursa-dgx1:2375'
docker.hostconfig = { network_mode = 'host', cpuset_cpus = '16-19,36-39' }

[[workers]]
name = 'dgx2-1'
arch = 'amd64'
docker.host = 'tcp://ursa-dgx2:2375'
docker.hostconfig = { network_mode = 'host', cpuset_cpus = '0-3,20-23' }

[[workers]]
name = 'dgx2-2'
arch = 'amd64'
docker.host = 'tcp://ursa-dgx2:2375'
docker.hostconfig = { network_mode = 'host', cpuset_cpus = '4-7,24-27' }

[[workers]]
name = 'dgx2-3'
arch = 'amd64'
docker.host = 'tcp://ursa-dgx2:2375'
docker.hostconfig = { network_mode = 'host', cpuset_cpus = '8-11,28-31' }

[[workers]]
name = 'dgx2-4'
arch = 'amd64'
docker.host = 'tcp://ursa-dgx2:2375'
docker.hostconfig = { network_mode = 'host', cpuset_cpus = '12-15,32-35' }

[[workers]]
name = 'dgx2-5'
arch = 'amd64'
docker.host = 'tcp://ursa-dgx2:2375'
docker.hostconfig = { network_mode = 'host', cpuset_cpus = '16-19,36-39' }

[[workers]]
name = 'jetson1'
arch = 'arm64v8'
docker.host = 'tcp://ursa-jetson1:2375'
docker.hostconfig = { network_mode = 'host' }
max_builds = 2
