# Copyright 2019 RStudio, Inc.
# All rights reserved.
#
# Use of this source code is governed by a BSD 2-Clause
# license that can be found in the LICENSE_BSD file.

url: 'https://ci.ursalabs.org/'
webui_port: 8010

secrets:
  enabled: true
  directory: '~/.ursalabs-pass'

hooks:
  github:
    enabled: true
    debug: false

auth:
  enabled: true
  roles:
    admin:
      orgs:
        - 'ursa-labs'
      users:
        - 'xhochy'
        - 'kou'
