# Copyright 2019 RStudio, Inc.
# All rights reserved.
#
# Use of this source code is governed by a BSD 2-Clause
# license that can be found in the LICENSE_BSD file.

###################### Buildmaster specific configurations ####################

url: 'https://ci.ursalabs.org/'
webui_port: 8100

secrets:
  enabled: true

######################### Project specific configurations #####################

arrow:
  # production arrow is hosted within another configuration alongside arrow
  # so only the configuration values under `ursabot` do matter in production

  reporters:
    github_status:
      enabled: true
      tokens:
        - '%(secret:kszucs/github_status_token)s'
        - '%(secret:pitrou/github_status_token)s'
    github_comment:
      enabled: true
      tokens:
        - '%(secret:ursabot/github_token)s'
    zulip_status:
      enabled: true
      organization: 'ursalabs'
      bot: 'ursabot-bot@ursalabs.zulipchat.com'
      stream: 'ursabot'
      apikey: '%(secret:ursabot/zulip_api_key)s'

  workers:
    - name: 'dgx1-1'
      arch: 'amd64'
      ncpus: 8
      docker:
        host: 'tcp://ursa-dgx1:2375'
        hostconfig:
          network_mode: 'host'
          cpuset_cpus: '0-3,20-23'

    - name: 'dgx1-2'
      arch: 'amd64'
      ncpus: 8
      docker:
        host: 'tcp://ursa-dgx1:2375'
        hostconfig:
          network_mode: 'host'
          cpuset_cpus: '4-7,24-27'

    - name: 'dgx1-3'
      arch: 'amd64'
      ncpus: 8
      docker:
        host: 'tcp://ursa-dgx1:2375'
        hostconfig:
          network_mode: 'host'
          cpuset_cpus: '8-11,28-31'

    - name: 'dgx1-4'
      arch: 'amd64'
      ncpus: 8
      docker:
        host: 'tcp://ursa-dgx1:2375'
        hostconfig:
          network_mode: 'host'
          cpuset_cpus: '12-15,32-35'

    - name: 'dgx1-5'
      arch: 'amd64'
      docker:
        host: 'tcp://ursa-dgx1:2375'
        hostconfig:
          network_mode: 'host'
          cpuset_cpus: '16-19,36-39'

    - name: 'dgx2-1'
      arch: 'amd64'
      tags:
        - cuda
      ncpus: 8
      docker:
        host: 'tcp://ursa-dgx2:2375'
        hostconfig:
          network_mode: 'host'
          cpuset_cpus: '0-3,20-23'

    - name: 'dgx2-2'
      arch: 'amd64'
      tags:
        - cuda
      ncpus: 8
      docker:
        host: 'tcp://ursa-dgx2:2375'
        hostconfig:
          network_mode: 'host'
          cpuset_cpus: '4-7,24-27'

    - name: 'dgx2-3'
      arch: 'amd64'
      tags:
        - cuda
      ncpus: 8
      docker:
        host: 'tcp://ursa-dgx2:2375'
        hostconfig:
          network_mode: 'host'
          cpuset_cpus: '8-11,28-31'

    - name: 'dgx2-4'
      arch: 'amd64'
      tags:
        - cuda
      ncpus: 8
      docker:
        host: 'tcp://ursa-dgx2:2375'
        hostconfig:
          network_mode: 'host'
          cpuset_cpus: '12-15,32-35'

    - name: 'dgx2-5'
      arch: 'amd64'
      tags:
        - cuda
      ncpus: 8
      docker:
        host: 'tcp://ursa-dgx2:2375'
        hostconfig:
          network_mode: 'host'
          cpuset_cpus: '16-19,36-39'

    - name: 'jetson1'
      arch: 'arm64v8'
      tags:
        - cuda
      ncpus: 8
      max_builds: 1
      docker:
        host: 'tcp://ursa-jetson1:2375'
        hostconfig:
          network_mode: 'host'
